# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-18 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='team',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='wiki.Team', verbose_name='所属团队'),
        ),
    ]
